groups/prometheus/iam-role.tf
groups/prometheus/locals.tf
groups/prometheus/main.tf
groups/prometheus/module-prometheus/alb.tf
groups/prometheus/module-prometheus/cloud-init.tf
groups/prometheus/module-prometheus/cloud-init/files/bootstrap-commands.yml
groups/prometheus/module-prometheus/cloud-init/templates/prometheus.yml.tpl
groups/prometheus/module-prometheus/instance.tf
groups/prometheus/module-prometheus/locals.tf
groups/prometheus/module-prometheus/polices-and-roles.tf
groups/prometheus/module-prometheus/security-groups.tf
groups/prometheus/module-prometheus/variables.tf
groups/prometheus/profiles/development-eu-west-2/common/vars
groups/prometheus/subnets.tf
groups/prometheus/variables.tf
groups/prometheus/vault-providers/approle
groups/prometheus/vault-providers/token
groups/prometheus/vault-providers/userpass
groups/prometheus/vault.tf
groups/prometheus/vpcs.tf

Add prometheus instance to the logging stack to monitor and alert on the elasticsearch instances.
Resolves: DVOP-1697

Add prometheus terraform

---

roles/kibana/tasks/manage-application-logs-index-patterns.yml
roles/kibana/tasks/manage-gateway-logs-index-patterns.yml

Add the environment name to the index patterns in Kibana to isolate each environment.

Add environment name to index patterns

---

roles/kibana/templates/application_logs_index_pattern.json.j2
roles/kibana/templates/gateway_logs_index_pattern.json.j2

Add environment name to the templates

Add environment name to the templates

---

index-lifecycle-management.yml
roles/index-lifecycle-management/defaults/main.yml
roles/index-lifecycle-management/tasks/main.yml
roles/index-lifecycle-management/templates/environment_ilm_policy.json.j2

Add index lifecycle management role

---

groups/bootstrap/profiles/development-eu-west-2/common/vars
groups/logging/profiles/development-eu-west-2/common/vars

Swap from latest -> version pattern
Resolves: DVOP-1603

Swap to versioned AMI

---

groups/grafana/locals.tf
groups/grafana/main.tf
groups/grafana/module-grafana/alb.tf
groups/grafana/module-grafana/locals.tf
groups/grafana/module-grafana/route53.tf
groups/grafana/module-grafana/variables.tf
groups/kibana/locals.tf
groups/kibana/main.tf
groups/kibana/module-kibana/alb.tf
groups/kibana/module-kibana/locals.tf
groups/kibana/module-kibana/route53.tf
groups/kibana/module-kibana/variables.tf
groups/prometheus/locals.tf
groups/prometheus/main.tf
groups/prometheus/module-prometheus/alb.tf
groups/prometheus/module-prometheus/locals.tf
groups/prometheus/module-prometheus/route53.tf
groups/prometheus/module-prometheus/variables.tf

Add conditional logic around the provisioning of certificates

---

groups/bootstrap/profiles/staging-eu-west-2/staging/vars
groups/elasticsearch/profiles/development-eu-west-2/common/vars
groups/elasticsearch/profiles/staging-eu-west-2/staging/vars
groups/elasticsearch/variables.tf
groups/grafana/profiles/staging-eu-west-2/staging/vars
groups/kibana/profiles/development-eu-west-2/common/vars
groups/kibana/profiles/staging-eu-west-2/staging/vars
groups/prometheus/profiles/staging-eu-west-2/staging/vars
groups/shared/profiles/staging-eu-west-2/staging/vars

Add staging profiles and missing common profiles from when kibana and elasticsearch modules were split.

Add staging profile to modules

---

groups/elasticsearch/remote-state.tf
groups/grafana/remote-state.tf
groups/kibana/remote-state.tf
groups/prometheus/remote-state.tf

Update remaining remote state files with parameterised variable replacing hardcoded value `development`

Update remaining remote state files with parameterised variable 

---

groups/grafana/module-grafana/alb.tf
groups/grafana/module-grafana/route53.tf
groups/kibana/main.tf
groups/kibana/module-kibana/alb.tf
groups/kibana/module-kibana/route53.tf
groups/kibana/variables.tf
groups/prometheus/module-prometheus/alb.tf
groups/prometheus/module-prometheus/route53.tf

Update lbs to be consistent with staging setup.
Increase Kibana to 3 instances to match current setup.

Loadbalancer changes for staging 

---

groups/grafana/locals.tf
groups/grafana/main.tf

Allow grafana API access to the concourse workers

---

groups/elasticsearch/profiles/development-eu-west-2/common/vars

Update instance type for master nodes as currently the spec is too low and we experienced issues in common stack as a result of this

Update instance type for master nodes development stack

---

roles/grafana/templates/logging_nodes_dashboard.json.j2

Adds monitoring for Kibana instances.
Minor changes to descriptions and grid sizes for visual purposes.

Add Kibana monitoring to Grafana graph

---

groups/bootstrap/cloud-init/templates/bootstrap-commands.yml.tpl
groups/elasticsearch/module-elasticsearch/cloud-init/templates/bootstrap-commands.yml.tpl
groups/elasticsearch/profiles/development-eu-west-2/common/vars
groups/elasticsearch/profiles/staging-eu-west-2/staging/vars
groups/grafana/module-grafana/cloud-init/templates/bootstrap-commands.yml.tpl
groups/kibana/module-kibana/cloud-init/templates/bootstrap-commands.yml.tpl
groups/kibana/profiles/staging-eu-west-2/staging/vars

Having calculated the disk size usage etc we have a new specification for the dev and staging logging stack.

New specification for development/staging logging stack

---

groups/elasticsearch/profiles/development-eu-west-2/devops/vars
groups/elasticsearch/profiles/live-eu-west-2/live/vars
groups/elasticsearch/profiles/staging-eu-west-2/staging/vars

Increase the disk space on live and staging logging stacks

Increase disk space on staging and live

---

groups/elasticsearch/locals.tf
groups/elasticsearch/main.tf
groups/elasticsearch/module-elasticsearch/cloud-init/templates/elasticsearch.yml.tpl
groups/elasticsearch/module-elasticsearch/cold-data-nodes.tf
groups/elasticsearch/module-elasticsearch/hot-data-nodes.tf
groups/elasticsearch/module-elasticsearch/master-nodes.tf
groups/elasticsearch/module-elasticsearch/variables.tf
groups/elasticsearch/module-elasticsearch/warm-data-nodes.tf

Add conditional configuration setting for master nodes only. Tidy up
role configuration output.
Add missing merge_type to master nodes
Resolves: DVOP-1880

Add availability zone attributes to nodes

---

groups/bootstrap/cloud-init/templates/elasticsearch-master.yml.tpl
groups/elasticsearch/module-elasticsearch/cloud-init/templates/elasticsearch.yml.tpl
groups/elasticsearch/module-elasticsearch/master-nodes.tf

Refactor routing configuration

---

groups/bootstrap/cloud-init/templates/bootstrap-commands.yml.tpl
groups/bootstrap/cloud-init/templates/elasticsearch-master.yml.tpl
groups/elasticsearch/locals.tf
groups/elasticsearch/main.tf
groups/elasticsearch/module-elasticsearch/cloud-init/templates/bootstrap-commands.yml.tpl
groups/elasticsearch/module-elasticsearch/cloud-init/templates/elasticsearch.yml.tpl
groups/elasticsearch/module-elasticsearch/cold-data-nodes.tf
groups/elasticsearch/module-elasticsearch/hot-data-nodes.tf
groups/elasticsearch/module-elasticsearch/master-nodes.tf
groups/elasticsearch/module-elasticsearch/variables.tf
groups/elasticsearch/module-elasticsearch/warm-data-nodes.tf
groups/kibana/module-kibana/cloud-init/templates/bootstrap-commands.yml.tpl
groups/prometheus/module-prometheus/cloud-init.tf
groups/prometheus/module-prometheus/cloud-init/files/bootstrap-commands.yml
groups/prometheus/module-prometheus/cloud-init/templates/bootstrap-commands.yml.tpl
groups/prometheus/module-prometheus/cloud-init/templates/system-config.yml.tpl

Add a volume resize message to the bootstrap-commands. This not only
provides more information but has the added benefit of forcing the
replacement of an instance when a volume size is changed.
Add volume resizing to the prometheus group
Resolves: DVOP-1880

Add volume resize message

---

groups/elasticsearch/locals.tf
groups/elasticsearch/main.tf
groups/elasticsearch/module-elasticsearch/cold-data-nodes.tf
groups/elasticsearch/module-elasticsearch/hot-data-nodes.tf
groups/elasticsearch/module-elasticsearch/variables.tf
groups/elasticsearch/module-elasticsearch/warm-data-nodes.tf
groups/elasticsearch/variables.tf

Simplify instance heap space configuration

---

groups/elasticsearch/locals.tf
groups/elasticsearch/main.tf
groups/elasticsearch/module-elasticsearch/alb.tf
groups/elasticsearch/module-elasticsearch/locals.tf
groups/elasticsearch/module-elasticsearch/route53.tf
groups/elasticsearch/module-elasticsearch/security-groups.tf
groups/elasticsearch/module-elasticsearch/variables.tf
groups/elasticsearch/profiles/development-eu-west-2/devops/vars

Add convenience load balancer

---

groups/elasticsearch/module-elasticsearch/route53.tf

Remove the sniffing route53 entry

---

groups/elasticsearch/profiles/development-eu-west-2/common/vars

Increase hot node disk from 10 -> 50

---

groups/elasticsearch/profiles/development-eu-west-2/common/vars

Resize cold and warm nodes from 10 -> 50

---

groups/elasticsearch/profiles/live-eu-west-2/live/vars

Add 3 extra cold nodes in live

---

roles/grafana/templates/logging_nodes_dashboard.json.j2

Updates the graph to add the additional volume and create alerting based on the same threshold as the data volume.
Resolves: DVOP-1975

Update kibana graph to include kibana_data volume

---

groups/elasticsearch-nodes-green/profiles/staging-eu-west-2/staging/vars

Add 6 warm nodes to cope with spike

---

groups/elasticsearch-alb/data.tf
groups/elasticsearch-alb/providers.tf

Update provider in keeping with terraform-lookup changes
